### ISSUE TITLE
Not work on Windows

### ISSUE THREAD

**Issue by eliasbobadilla** [UltiRequiem/nfacu#1]
The application doesn't work on Windows environment. 

Input: 
```sh
.\nfacu.exe C:\repos\DotnetSample\nfacu.json
```
Expected: The app.config files in project updated with nfacu.json values

Result: the files haven't changed

**Comment by UltiRequiem** [comment]
Solved on:
https://github.com/UltiRequiem/nfacu/commit/d295998935e0a2191a1d550e0bb3863cadfd3d23

**Comment by UltiRequiem** [comment]
Should be working now.
